[package]
name = "ubiquisync-core"
description = "Core protocol types and sync engine for Ubiquisync — conflict-free sync of structured data over commodity cloud storage or a dedicated server."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true }
blake3 = { workspace = true }
futures-channel = { workspace = true }
futures-core = { workspace = true }
thiserror = { workspace = true }
aes-gcm-siv = { workspace = true }
num_enum = { workspace = true }
ed25519-dalek = { workspace = true }
p256 = { workspace = true }
zeroize = { workspace = true }
secrecy = { workspace = true }
getrandom = { workspace = true }

[target.'cfg(target_vendor = "apple")'.dependencies]
security-framework =  { workspace = true }
security-framework-sys =  { workspace = true }

[dev-dependencies]
futures = { workspace = true }
pollster = { workspace = true }
proptest = { workspace = true }
test-strategy = { workspace = true }
test-case = { workspace = true }
crypto-common = { workspace = true }

[lints]
workspace = true
