[package]
name = "ubiquisync"
description = "Conflict-free sync of structured data over commodity cloud storage or a dedicated server."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["sqlite"]
sqlite = ["dep:ubiquisync-sqlite"]
postgres = ["dep:ubiquisync-postgres"]

[dependencies]
ubiquisync-core = { workspace = true }
ubiquisync-tables = { workspace = true }
ubiquisync-postgres = { workspace = true, optional = true }
ubiquisync-sqlite = { workspace = true, optional = true }

[lints]
workspace = true
