//! Hybrid logical clock: the timestamp value type, the pure clock, and the
//! shared persistent service.
//!
//! Every log entry carries a [`Timestamp`] generated by a hybrid logical
//! clock ([`Hlc`]). Each tick is strictly greater than the last and respects
//! causality across peers, so a peer's entry stream is monotonically
//! non-decreasing and all LWW merge decisions reduce to comparing these
//! timestamps.
//!
//! - [`timestamp`] — the packed `Timestamp` representation and its ordering.
//! - [`clock`] — the pure in-memory `Hlc`, the wall-clock source, and the skew bound.
//! - [`service`] — `HlcService`, the lock-protected, persistent handle subsystems hold.

mod clock;
mod service;
mod timestamp;

pub use clock::{wall_ms, Hlc, SkewError, MAX_SKEW_MS};
pub use service::{HlcError, HlcService, HlcStorage};
pub use timestamp::Timestamp;
