//! Hybrid logical clock: the timestamp value type, the pure clock, and the
//! shared persistent service.
//!
//! Every log entry carries a [`Timestamp`] generated by a hybrid logical
//! clock ([`Hlc`]). Each tick is strictly greater than the last and respects
//! causality across peers, so a peer's entry stream is monotonically
//! non-decreasing and all LWW merge decisions reduce to comparing these
//! timestamps.
//!
//! - [`Timestamp`] — the packed instant representation and its ordering.
//! - [`Hlc`] — the pure in-memory clock, with [`wall_ms`] and the skew bound
//!   ([`SkewError`] / [`MAX_SKEW_MS`]).
//! - [`HlcService`] — the lock-protected, persistent handle subsystems hold,
//!   backed by [`HlcStorage`].

mod clock;
mod service;
mod timestamp;

pub use clock::{wall_ms, Hlc, SkewError, MAX_SKEW_MS};
pub use service::{HlcError, HlcService, HlcStorage};
pub use timestamp::Timestamp;
