[package]
name = "demo-app"
version = "0.1.0"
authors = ["Aaron C <aaronc@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.10", features = [] }
loro_fractional_index = "1.13.0"
borsh = { version = "1.8.1", features = ["derive"] }

ubiquisync-core = { workspace = true }
ubiquisync-sql = { workspace = true }
ubiquisync-tables = { workspace = true }
pastey = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
test-strategy = { workspace = true }
insta = { workspace = true }

[features]
default = ["desktop"]
# The feature that are only required for the desktop = ["dioxus/desktop"] build target should be optional and only enabled in the desktop = ["dioxus/desktop"] feature
desktop = ["dioxus/desktop"]
# The feature that are only required for the mobile = ["dioxus/mobile"] build target should be optional and only enabled in the mobile = ["dioxus/mobile"] feature
mobile = ["dioxus/mobile"]
